# Generated by Django 5.0.3 on 2024-11-03 05:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=accounts.models.generate_unique_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
