# Generated by Django 5.0.3 on 2024-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_address_product_city_product_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='href',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
