# Generated by Django 5.0.3 on 2024-10-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='href',
        ),
    ]
