# Generated by Django 5.0.3 on 2024-10-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wallbanners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallbanners',
            name='product_url',
        ),
        migrations.AddField(
            model_name='wallbanners',
            name='background_is_light',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallbanners',
            name='first_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallbanners',
            name='second_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
