# Generated by Django 5.0.3 on 2024-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_wallbanners_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallbanners',
            name='first_url_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wallbanners',
            name='second_url_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
