# Generated by Django 5.0.3 on 2024-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('max_amount_bid', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(blank=True, choices=[('rejected', 'rejected'), ('pending', 'pending'), ('accepted', 'accepted'), ('winner', 'winner')], default='pending', max_length=10, null=True),
        ),
    ]
