# Generated by Django 5.0.3 on 2024-10-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_scorelevel_alter_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(blank=True, choices=[('rejected', 'rejected'), ('pending', 'pending'), ('accepted', 'accepted'), ('winner', 'winner')], max_length=10, null=True),
        ),
    ]
